name: aihealth_lab
channels:
  - defaults
dependencies:
  - python=3.8.1
  - pandas=1.0.1
  - matplotlib=3.1.3
  - lxml=4.5.0
  - openpyxl
  - jupyter
  - jupyterlab
  - ipykernel
  - pip
  - pip:
      - quickumls
